### ISSUE TITLE
Can't run e3-testsuite under GHA's windows platform

### ISSUE THREAD

**Issue by thvnx** [AdaCore/e3-testsuite#107]
I'm facing an issue on GitHub Actions, when running e3-testsuite on windows. The issue concerns the rlimit tool from e3-core, I get the following message:

```
rlimit: cannot spawn process (error 0x5)
```

Looks like it's a known issue: https://github.com/AdaCore/e3-testsuite/blob/a89b4011250154d499f545ff4e10369f5f611d40/.github/workflows/ci.yaml#L13-L14, which seems to have been partially addressed by https://github.com/AdaCore/e3-core/commit/ed39720dca9debe57feb39e849d15bce42699fb6.

Is there something I should set in the GHA runner to make it work?

Thanks!

**Comment by thvnx** [comment]
Sorry for the noise, it works as expected. I just forgot to pip install e3-core from the master's branch 🤦.

- Do you plan to publish a new release on Pypi?
- I guess you can add back `windows-latest` in the CI script!

**Comment by pmderodat** [comment]
As you have noticed, this issue is related to e3-core: I suggest to contact the team responsible for e3-core, they should be able to answer your two questions (I can’t). Thanks!
