### ISSUE TITLE
xunit output: escape output text when adding it to the .xml

### ISSUE THREAD

**Issue by setton** [AdaCore/e3-testsuite#113]
The text put in the `<system-out>` node is already escaped for XML inclusion, but it needs to be stripped from control characters as well, such as `^[2J^[H` which can be used to print coloured output in terminal. (Observed in the gnatfuzz testsuite)

**Comment by pmderodat** [comment]
Hello Nico,

That’s indeed a blind spot in e3-testsuite: although ANSI sequences are already automatically disabled when logs don’t end up in a TTY, CIs generally run in a TTY and thus have colors which can clutter further processings. There was no simple way to just disable colors, whereas other e3 tools have `--nocolor` to do this. I’ve opened #114 to do the same in e3-testsuite: once it is merged, I recomment passing `--nocolor` in the CI scripts for gnatfuzz’ testsuite.
