### ISSUE TITLE
Use of Python 3.8 features

### ISSUE THREAD

**Issue by LordAro** [AdaCore/e3-testsuite#93]
Specifically, of `typing.Protocol` in a couple of places:

https://github.com/AdaCore/e3-testsuite/blob/7cbb9365f093820a4045d52975c358a3e8b12454/src/e3/testsuite/fragment.py#L40-L42

https://github.com/AdaCore/e3-testsuite/blob/7cbb9365f093820a4045d52975c358a3e8b12454/src/e3/testsuite/report/display.py#L78-L80

There doesn't seem to be any specifically defined minimum Python version in this repo, but libadalang/langkit/e3-core do specify 3.7, so I guess this would inherit from that?

**Comment by pmderodat** [comment]
Hello,

Thank you for pointing this out. Unlike what’s advertised, e3-core currently supports only Python 3.8 and Python 3.9, so e3-testsuite has the same constraint: I’ll add this info to e3-testsuite’s README and to the doc for Libadalang/Langkit’s testsuites (this does not impact the rest of these projects).

**Comment by LordAro** [comment]
I thought that might be the case, thanks for confirming!

**Comment by pmderodat** [comment]
You are welcome! The READMEs are now up-to-date, and e3-testsuite’s testing uses Python 3.8 to detect future incompatibilities.
